<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Stripboard.Application\Stripboard.Application.csproj" />
    <ProjectReference Include="..\Stripboard.Infrastructure\Stripboard.Infrastructure.csproj" />
    <ProjectReference Include="..\Stripboard.Mcp.Schedule\Stripboard.Mcp.Schedule.csproj">
      <ExcludeAssets>contentFiles</ExcludeAssets>
    </ProjectReference>
    <ProjectReference Include="..\Stripboard.CallSheets\Stripboard.CallSheets.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

</Project>
