"""
Writes a feature-length screenplay and its breakdown, for the EV-38 scale benchmark.

The demo screenplays are 6 to 14 scenes. A real feature is 90 to 130, across 20-plus
locations, and the honest question a judge asks is whether CP-SAT still answers at that size
or quietly stops proving anything. A 14-scene fixture cannot answer that.

This is a generator rather than a checked-in wall of prose because the *distribution* is what
the solver reacts to, and a generator lets that distribution be stated instead of guessed at:

  - **Cast follows a call sheet, not a uniform draw.** Two leads carry most of the picture,
    four supporting parts recur, eight day players appear once or twice. A uniform cast would
    make Day Out of Days trivial and the benchmark meaningless.
  - **Locations repeat unevenly.** Six standing sets take about half the scenes; twenty are
    visited once or twice. That is what makes company moves worth minimising.
  - **Night scenes cluster in the last third**, because a schedule that can bank them is the
    one the union turnaround rule bites on.

Deterministic: same seed, same screenplay, so the published figures can be reproduced.

    python demo/make_longform_screenplay.py

Writes two files. The `.fountain` is what the breakdown agent reads when the question is
extraction; the `.breakdown.json` is what the solver reads when the question is scale. They
are separate on purpose — a benchmark whose input varies with a model's mood is measuring the
wrong thing.
"""

import json
import random
from pathlib import Path

SEED = 20260807
TARGET_SCENES = 112

STANDING_SETS = [
    ("PRECINCT HOUSE", ["SQUAD ROOM", "INTERVIEW ROOM", "EVIDENCE CAGE", None]),
    ("HARBOUR MASTER'S OFFICE", ["FRONT DESK", "BACK ROOM", None]),
    ("VELASCO APARTMENT", ["KITCHEN", "BEDROOM", "HALLWAY", None]),
    ("THE ANCHORAGE PUB", ["BAR", "SNUG", "CELLAR", None]),
    ("CONTAINER TERMINAL", ["CRANE GANTRY", "YARD OFFICE", None]),
    ("CITY MORGUE", ["AUTOPSY SUITE", "COLD STORE", None]),
]

SINGLE_VISIT = [
    "DISUSED GRAIN SILO", "RIVERSIDE FOOTPATH", "MULTI-STOREY CAR PARK",
    "ST BRENDAN'S CHURCH", "COASTGUARD STATION", "FERRY TERMINAL",
    "ALLOTMENT GARDENS", "MAGISTRATES COURT", "TOWER BLOCK STAIRWELL",
    "SCRAPYARD", "NIGHT BUS", "LOCK-UP GARAGE", "HOSPITAL CORRIDOR",
    "SEAFRONT PROMENADE", "RADIO STATION BOOTH", "CUSTOMS SHED",
    "BOARDING HOUSE LANDING", "CANAL TOWPATH", "DERELICT LIDO",
    "MOTORWAY SERVICES",
]

LEADS = ["DI ROSA VELASCO", "MARCUS OYELARAN"]
SUPPORTING = ["DS PRIYA CHANDRA", "HARBOUR MASTER FINN", "DR AUGUSTINE BELL", "NELL KEATING"]
DAY_PLAYERS = [
    "CUSTOMS OFFICER", "BARMAN", "CORONER'S ASSISTANT", "DUTY SOLICITOR",
    "CRANE OPERATOR", "NIGHT NURSE", "RADIO PRODUCER", "TEENAGE WITNESS",
]

ACTIONS = [
    "The room holds the kind of quiet that follows a shouted question.",
    "Rain finds the gap in the window frame it always finds.",
    "A file lands on the desk heavier than the paper in it justifies.",
    "Somewhere below, a chain runs out and stops.",
    "The light through the blinds moves a hand's width and settles.",
    "Two coffees go cold in the time it takes to say nothing.",
    "A phone buzzes face-down and is ignored.",
    "The door does not close properly and nobody gets up to fix it.",
]

LINES = [
    "That's not what the manifest says.",
    "Then the manifest is wrong, or somebody is.",
    "Give me until the tide turns.",
    "You've had three tides.",
    "I'm not asking you to like it.",
    "Nobody signs for a container that isn't there.",
    "Somebody did.",
    "Write it down. All of it.",
]

HEADER = [
    "Title: The Tide Turns",
    "Credit: Written by",
    "Author: The Stripboard Project",
    "Draft date: 2026-08-07",
    "Contact: Generated by demo/make_longform_screenplay.py for the EV-38 scale benchmark.",
    "",
    "Notes: Feature length and deliberately uneven. Two leads carry the picture, four",
    "supporting parts recur and eight day players appear once or twice; six standing sets take",
    "about half the scenes and twenty locations are visited once or twice. That distribution is",
    "what makes Day Out of Days, company moves and night banking worth solving — a uniform",
    "screenplay would let any scheduler look competent.",
    "",
]


def build():
    """Returns the Fountain text and the scene records behind it."""
    rng = random.Random(SEED)

    pool = []
    for location, sets in STANDING_SETS:
        pool.extend([(location, sets)] * 9)
    for location in SINGLE_VISIT:
        pool.extend([(location, [None])] * 2)

    lines = list(HEADER)
    scenes = []

    for number in range(1, TARGET_SCENES + 1):
        location, sets = rng.choice(pool)
        set_name = rng.choice(sets)
        heading_place = f"{location} - {set_name}" if set_name else location

        int_ext = "INT." if rng.random() < 0.68 else "EXT."
        night_bias = 0.20 if number < TARGET_SCENES * 0.66 else 0.55
        day_night = "NIGHT" if rng.random() < night_bias else "DAY"

        cast = [lead for lead in LEADS if rng.random() < 0.55]
        cast += [actor for actor in SUPPORTING if rng.random() < 0.18]
        if rng.random() < 0.22:
            cast.append(rng.choice(DAY_PLAYERS))
        if not cast:
            cast.append(rng.choice(LEADS))

        body = [rng.choice(ACTIONS), ""]
        for speaker in cast[:2]:
            body += [speaker, rng.choice(LINES), ""]
        tail_beat = rng.random() < 0.34
        if tail_beat:
            body += [rng.choice(ACTIONS), ""]

        lines.append(f"{int_ext} {heading_place} - {day_night}")
        lines.append("")
        lines.extend(body)

        scenes.append({
            "number": number,
            "location": location,
            "set": set_name,
            "int_ext": int_ext.rstrip("."),
            "day_night": day_night,
            # Between an eighth and a page and a half, tracking how much is on the page.
            "eighths": 2 + len(cast) * 2 + (3 if tail_beat else 0),
            "synopsis": f"Scene {number} at {heading_place}.",
            "cast": cast,
        })

    return "\n".join(lines) + "\n", scenes


def breakdown(scenes):
    """The generator's own breakdown, in the shape `/api/breakdown/import` accepts.

    `source` says "generator" rather than "gemini" because a field that records where data
    came from has to say the true thing even when nothing is checking it.
    """
    return {
        "source": "generator",
        "scenes": [
            {
                "number": s["number"],
                "location": s["location"],
                "set_name": s["set"],
                "int_ext": s["int_ext"],
                "day_night": s["day_night"],
                "eighths": s["eighths"],
                "synopsis": s["synopsis"],
                "cast": s["cast"],
                "elements": [],
            }
            for s in scenes
        ],
    }


if __name__ == "__main__":
    text, scenes = build()

    fountain = Path(__file__).with_name("screenplay-longform.fountain")
    fountain.write_text(text, encoding="utf-8", newline="\n")

    payload = Path(__file__).with_name("screenplay-longform.breakdown.json")
    payload.write_text(json.dumps(breakdown(scenes), indent=1), encoding="utf-8", newline="\n")

    locations = {s["location"] for s in scenes}
    cast = {name for s in scenes for name in s["cast"]}
    nights = sum(1 for s in scenes if s["day_night"] == "NIGHT")

    print(f"{fountain.name}: {len(scenes)} scenes, {len(locations)} locations, "
          f"{len(cast)} speaking parts, {nights} night scenes")
    print(f"{payload.name}: breakdown for the solver benchmark")
